service: serverless-lambda-chaining

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

functions:
  firstLambda:
    handler: handler.firstLambda
  secondLambda:
    handler: handler.secondLambda
    events:
      - sns: dispatcher
